stages:
  - test

variables:
  XREFCHECK_URL: "https://github.com/serokell/xrefcheck/releases/download/v0.2/xrefcheck-x86_64-linux"

verify-doc-links:
  stage: test
  allow_failure: false
  only:
    refs:
      - merge_requests
  script:
    - wget -O xrefcheck "$XREFCHECK_URL" && chmod +x ./xrefcheck && ./xrefcheck --no-progress --ignored xrefcheck --mode local-only

# In case it is necessary to exclude some links from checking,
# see the Special functionality section of xrefcheck README.
# https://github.com/serokell/xrefcheck#special-functionality
verify-doc-external-links:
  stage: test
  allow_failure: true
  retry:
    max: 1
    when: script_failure
  only:
    refs:
      - merge_requests
  script:
    - wget -O xrefcheck "$XREFCHECK_URL" && chmod +x ./xrefcheck && ./xrefcheck --no-progress --ignored xrefcheck --mode external-only
