# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: Unlicense

# Parameters of repository traversal.
traversal:
  # Files and folders which we pretend do not exist
  # (so they are neither analyzed nor can be referenced).
  ignored:
    # Git files
    - .git

# Verification parameters.
verification:
  # On 'anchor not found' error, how much similar anchors should be displayed as
  # hint. Number should be between 0 and 1, larger value means stricter filter.
  anchorSimilarityThreshold: 0.5

  # When checking external references, how long to wait on request before
  # declaring "Response timeout".
  externalRefCheckTimeout: 10s

  # Prefixes of files, references in which should not be analyzed.
  notScanned:
    - .gitlab/merge_request_templates/
    - .gitlab/issue_templates/

  # Glob patterns describing the files which do not physically exist in the
  # repository but should be treated as existing nevertheless.
  virtualFiles:
    - ../../issues
    - ../../issues/*
    - ../../merge_requests
    - ../../merge_requests/*

# Parameters of scanners for various file types.
scanners:

  markdown:
    # Type of repository.
    #
    # This affects which anchors are generated for headers.
    flavor: GitLab
